### ISSUE TITLE
 Add general JSD (w/ beta) support

### ISSUE THREAD

**Issue by qingquansong** [linkedin/Liger-Kernel#278]
### 🚀 The feature, motivation and pitch

We have had a great JSD kernel implemented in this [PR](https://github.com/linkedin/Liger-Kernel/pull/264) and this request is for helping extend with an optional beta arg to create the mixed distribution between student and teacher. When beta=0, it should be equivalent to forward KL and beta=1 it should be equivalent to reverse KL. Note: the corner case could be tricky. More details can be found in paper: https://arxiv.org/abs/2306.13649

**Comment by Tcc0403** [comment]
I've done the general JSD forward and gradients calculations for beta in (0, 1). 
For corner cases when beta = 0 or 1, I think it would be easier just directly call forward KL and reverse KL respectively. 
Since forward KL and general JSD still differ by a scalar multiple when beta is close to 0, and so is reverse KL.
Equation 14-17 in paper: https://arxiv.org/pdf/1511.05101

**Comment by yundai424** [comment]
@Tcc0403 yeah i feel it makes sense to just add a check to validate $\beta$ in (0, 1), agree with you that for beta=0 or 1 it's better just to use the standard F/RKL to avoid confusion and duplicated implementation 🤔

**Comment by Tcc0403** [comment]
Should I add beta support directly on #264 or wait for the merge?

**Comment by qingquansong** [comment]
@Tcc0403 Let's create the separate pr for it. I can ship the #264 after the GPU CI test got fixed. Thanks for the efforts!
