### ISSUE TITLE
Move from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by ByronHsu** [linkedin/Liger-Kernel#72]
### 🚀 The feature, motivation and pitch

As recommended in https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by mohammadpagard** [comment]
Hello, I was trying to fork your project, but the packages are too large and take a long to install, so I want to upload the project file in this box, but the file format is .txt because GitHub doesn't let me upload .py :)
[pyproject.txt](https://github.com/user-attachments/files/16737608/pyproject.txt)

Good luck :)

**Comment by mohammadpagard** [comment]
I sent the pull requested

**Comment by shimizust** [comment]
Fixed with #150
